import type { Handler } from "@netlify/functions";

const handler: Handler = async function(event) {
  if (event.body === null) {
    return {
      statusCode: 400,
      body: JSON.stringify("Payload required"),
    };
  }

  const requestBody = JSON.parse(event.body) as {
    purchaseName: string;
    purchaseEmail: string;
  };

  const response = await fetch(
    `${process.env.URL}/.netlify/functions/emails/purchase`,
    {
      method: "POST",
      headers: {
        // This secret is auto-generated by Netlify when you enable the integration
        "netlify-emails-secret": process.env.NETLIFY_EMAILS_SECRET || "",
      },
      body: JSON.stringify({
        from: "orders@ladwine.com",
        to: requestBody.purchaseEmail,
        subject: "Expect your order soon!",
        parameters: {
          customerName: requestBody.purchaseName,
        },
      }),
    });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Netlify Email API error: ${errorText}`);
  }

  return {
    statusCode: 200,
    body: JSON.stringify({ message: "Order email triggered via Netlify Integration" }),
  };
};

export { handler };
